name: Build Termux Standalone Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-termux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for ARM64 Emulation
        uses: docker/setup-qemu-action@v3

      - name: Build Standalone Binary inside Termux Environment
        run: |
          mkdir -p ${{ github.workspace }}/build
          sudo chmod -R 777 ${{ github.workspace }}

          docker run --rm -v ${{ github.workspace }}:/workspace termux/termux-docker:aarch64 bash -c "
            pkg update -y && pkg upgrade -y
            pkg install python clang build-essential patchelf zstd ccache termux-elf-cleaner ldd binutils -y

            pip install -r /workspace/client_requirements.txt
            pip install nuitka

            WORK_DIR=\$HOME/work
            mkdir -p \$WORK_DIR
            cp -r /workspace/* \$WORK_DIR/
            cd \$WORK_DIR

            nuitka --standalone \
                   --onefile \
                   --lto=yes \
                   --remove-output \
                   --output-dir=build_out \
                   --output-filename=termux_client_arm64 \
                   client.py

            strip build_out/termux_client_arm64

            cp build_out/termux_client_arm64 /workspace/build/
          "


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/termux_client_arm64
          generate_release_notes: true