name: Build x86_64 

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]  # بناء نسختين
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r client_requirements.txt

      - name: Install Nuitka
        run: pip install nuitka

      - name: Build standalone binary with Nuitka
        run: |
          nuitka --standalone --onefile \
                 --output-dir=build \
                 --output-filename=worker_${{ matrix.os }} \
                 client.py

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: client_${{ matrix.os }}
      #     path: build/worker_${{ matrix.os }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Build ${{ github.run_number }}
          files: build/worker_${{ matrix.os }}
          generate_release_notes: true